### ISSUE TITLE
Chinese environment not translated

### ISSUE THREAD

**Issue by jioce** [kubesphere/kubesphere#5149]
**Describe the Bug**
![image](https://user-images.githubusercontent.com/88183150/185050492-dc468333-4651-443e-8928-6009904633e1.png)

![image](https://user-images.githubusercontent.com/88183150/185050554-068fe264-08f8-4ee7-be99-2d34803bd7eb.png)

![image](https://user-images.githubusercontent.com/88183150/185050597-17c9a6b6-6862-48ac-a793-869390f591f6.png)

**Versions Used**
KubeSphere: v3.3.1-rc.0

/kin bug
/assign @patrickluoyu 
/priority high

**Comment by wenxin-01** [comment]
![image](https://user-images.githubusercontent.com/68640256/185054374-df438c4e-625d-40a7-9f40-829a27c6b874.png)

**Comment by harrisonliu5** [comment]
this PR https://github.com/kubesphere/console/pull/3589  fix the issue by wenxin.

**Comment by jioce** [comment]
There are still untranslated parts
![image](https://user-images.githubusercontent.com/88183150/190547899-a6f7e445-0b84-44cf-a6ee-1f841a4e5fb5.png)

version used：kubesphere v3.3.1-rc.2

**Comment by jioce** [comment]
![image](https://user-images.githubusercontent.com/88183150/190550155-300231ff-c776-4150-9c69-e1e467cdfd53.png)

**Comment by wenxin-01** [comment]
![image](https://user-images.githubusercontent.com/68640256/190588967-f744c359-d02f-475f-ad39-8f8cdcd7a7a8.png)

**Comment by wenxin-01** [comment]
![image](https://user-images.githubusercontent.com/68640256/190589836-dca5835a-c5a6-4297-a586-e2fa6ff77d5d.png)

**Comment by jioce** [comment]
![image](https://user-images.githubusercontent.com/88183150/190612122-0c909936-19ff-4718-9c35-4e8e779bba60.png)

**Comment by wenxin-01** [comment]
![image](https://user-images.githubusercontent.com/68640256/190941322-336bcbd1-c7d8-4936-b6e5-aa966726c545.png)

**Comment by jioce** [comment]
<img width="960" alt="1663557964902" src="https://user-images.githubusercontent.com/88183150/190945329-ff4f06d1-b358-4bb6-af0c-2c4a357d833c.png">

**Comment by wenxin-01** [comment]
![image](https://user-images.githubusercontent.com/68640256/190957205-e1169514-a294-4c78-82ef-cdce8340c43b.png)

![image](https://user-images.githubusercontent.com/68640256/190957229-7b9d06ef-b77a-413d-9d97-2296991cecfd.png)

**Comment by jioce** [comment]
![image](https://user-images.githubusercontent.com/88183150/190958681-a2ee92bc-f533-4e98-b5c6-89efc0381522.png)

**Comment by jioce** [comment]
![image](https://user-images.githubusercontent.com/88183150/190960439-01e580c3-ab0d-4dfa-96ca-06d9dbba1c8f.png)

**Comment by wenxin-01** [comment]
![image](https://user-images.githubusercontent.com/68640256/190970570-53237de7-1c01-4570-961e-e43fb0431bec.png)

**Comment by wenxin-01** [comment]
![image](https://user-images.githubusercontent.com/68640256/190972255-39edb9eb-c62e-48c6-b2ec-177997c70abf.png)

**Comment by patrickluoyu** [comment]
Fixed in PRs [3739](https://github.com/kubesphere/console/pull/3739), [3743(]https://github.com/kubesphere/console/pull/3743), and [3748](https://github.com/kubesphere/console/pull/3748).

**Comment by jioce** [comment]
![image](https://user-images.githubusercontent.com/88183150/190980048-87a3e6ad-767c-4b48-a5ab-3bc6985d261c.png)

![image](https://user-images.githubusercontent.com/88183150/190980111-0412329c-efed-414e-9cd6-04872c9b4ef9.png)

**Comment by patrickluoyu** [comment]
> ![image](https://user-images.githubusercontent.com/68640256/190972255-39edb9eb-c62e-48c6-b2ec-177997c70abf.png)

This is caused by a change in the backend code and the change is incorrect. The backend code needs to be reverted to resolve this issue, which has been confirmed by @wansir.

**Comment by wenxin-01** [comment]
v3.3.1-rc.3 
![image](https://user-images.githubusercontent.com/68640256/192680789-97b81f88-b478-4b56-ab46-64864a4b713a.png)

**Comment by jioce** [comment]
issue is still exist in v3.3.1-rc.3
![image](https://user-images.githubusercontent.com/88183150/192932227-db91501a-fc95-468b-86de-371bf21a3619.png)

**Comment by zhou1203** [comment]
> issue is still exist in v3.3.1-rc.3 ![image](https://user-images.githubusercontent.com/88183150/192932227-db91501a-fc95-468b-86de-371bf21a3619.png)

Fixed in PR https://github.com/kubesphere/ks-installer/pull/2122

**Comment by wenxin-01** [comment]
ADD_CLUSTER_FOR_WORKSPACE @patrickluoyu 
![image](https://user-images.githubusercontent.com/68640256/194788868-ab0fee3e-ad35-4c11-b1a6-22b107d26b11.png)

**Comment by patrickluoyu** [comment]
Fixed in https://github.com/kubesphere/console/pull/3799.

**Comment by wenxin-01** [comment]
CONFIGMAP_EMPTY_DESC @patrickluoyu 
![image](https://user-images.githubusercontent.com/68640256/194820508-d99d04de-8139-47a1-a053-dfcf3acac23c.png)

**Comment by wenxin-01** [comment]
![image](https://user-images.githubusercontent.com/68640256/195271840-29495782-9e5b-456a-9b03-7c2a9d292c07.png)
@patrickluoyu

**Comment by patrickluoyu** [comment]
Fixed in https://github.com/kubesphere/console/pull/3825.

**Comment by wenxin-01** [comment]
![image](https://user-images.githubusercontent.com/68640256/195800747-acf7720b-e6a6-40f0-af90-23ee8be9ec1c.png)
@patrickluoyu  `v3.3.1-rc.4`

**Comment by wenxin-01** [comment]
![image](https://user-images.githubusercontent.com/68640256/195801898-e013d7c5-84d5-4c90-84b8-653aab3da9e1.png)

**Comment by wenxin-01** [comment]
`v3.3.1-rc.4`
![image](https://user-images.githubusercontent.com/68640256/196329120-ab40543d-e789-43ef-8cca-30f5ba054297.png)

**Comment by patrickluoyu** [comment]
Fixed in https://github.com/kubesphere/console/pull/3849

**Comment by wenxin-01** [comment]
![image](https://user-images.githubusercontent.com/68640256/197091512-fe8446d8-b12e-4c34-816b-4eefb67cdf63.png)

**Comment by wenxin-01** [comment]
Issue fixed in `kubespheredev/ks-console:nightly-20221025`
